//user actions
export const GETWATCHLISTDATA="GETWATCHLISTDATA"
export const ADDWATCHlIST="ADDWATCHlIST"
export const REMOVEWATCHlIST="REMOVEWATCHlIST"
export const GET_WATCH_LIST_START="GET_WATCH_LIST_START"
export const GET_WATCH_LIST_SUCCESS="GET_WATCH_LIST_SUCCESS"
export const GET_IFSC_DETAILS_START="GET_IFSC_DETAILS_START"
export const GET_IFSC_DETAILS_SUCCESS="GET_IFSC_DETAILS_SUCCESS"
export const GET_IFSC_DETAILS_ERROR="GET_IFSC_DETAILS_ERROR"


//Kin Action 
export const ADD_KIN_START="ADD_KIN_START"
export const DELETE_KIN_START="DELETE_KIN_START"

export const ADD_LOCATION_TITLE_START="ADD_LOCATION_TITLE_START"
export const DELETE_LOCATION_TITLE_START="DELETE_LOCATION_TITLE_START"




//admin stock action 
export const ADDSTOCKS="ADDSTOCKS"
export const UPDATESTOCKS="UPDATESTOCKS"
export const REMOVESTOCK="REMOVESTOCK"
export const GET_STOCKS_LIST="GET_STOCKS_LIST"

export const GET_STOCKS_LIST_START = "GET_STOCKS_LIST_START"
export const GET_STOCKS_LIST_SUCCESS = "GET_STOCKS_LIST_SUCCESS"

export const ADD_STOCK_START = "ADD_STOCK_START"
export const ADD_STOCK_SUCCESS = "ADD_STOCK_SUCCESS"

export const UPDATE_STOCK_START = "UPDATE_STOCK_START"
export const UPDATE_STOCK_SUCCESS = "UPDATE_STOCK_SUCCESS"

export const REMOVE_STOCK_START = "REMOVE_STOCK_START"
export const REMOVE_STOCK_SUCCESS = "REMOVE_STOCK_SUCCESS"


// add members  by admin and signup actions
export const GETMEMBERSDATA="GETMEMBERSDATA"
export const ADDMEMBERS="ADDMEMBERS"
export const GETUSERDATA="GETUSERDATA";
export const GET_MEMBERDATAS_START="GET_MEMBERDATAS_START";
export const GET_SINGLE_MEMBERDATAS_START="GET_SINGLE_MEMBERDATAS_START";
export const GET_SINGLE_MEMBERDATAS_SUCCESS="GET_SINGLE_MEMBERDATAS_SUCCESS";
export const GET_MEMBERDATAS_SUCCESS="GET_MEMBERDATAS_SUCCESS";
export const ADD_MEMBERS_START="ADD_MEMBERS_START";
export const ADD_MEMBERS_SUCCESS="ADD_MEMBERS_SUCCESS";
export const UPDATE_MEMBERDATA_START="UPDATE_MEMBERDATA_START";
export const UPDATE_MEMBERDATA_SUCCESS="UPDATE_MEMBERDATA_SUCCESS";
export const STORE_FORGET_MEMBERDATA="STORE_FORGET_MEMBERDATA";

export const SET_COUNTERVALUE_START="SET_COUNTERVALUE_START";


//admin News Actions
export const GET_NEWS_LIST="GET_NEWS_LIST"
export const GET_NEWS_lIST_START="GET_NEWS_lIST_START"
export const GET_NEWS_lIST_SUCCESS="GET_NEWS_lIST_SUCCESS"



// Dynamic api state
export function pending (actionName){
    return actionName+"_PENDING"
}
export function fulfilled  (actionName){
    return actionName+"_FULFILLED"
}
export function rejected (actionName){
    return actionName+"_REJECTED"
}

// LOGIN USER
export const LOGIN_USER_START = "LOGIN_USER_START"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_SAVE = "LOGIN_USER_SAVE"
export const SET_VALID_USER = "SET_VALID_USER"

//error
export const ERROR_MESSAGE = "ERROR_MESSAGE"



//Token
export const GET_DATABY_TOKEN_START = "GET_DATABY_TOKEN_START"
export const GET_DATABY_TOKEN_SUCCESS = "GET_DATABY_TOKEN_SUCCESS"