const conf = {
    "appSource": "12122",
    "appName": "5P51082513",
    "userId": "E6DVHrr7MuW",
    "password": "ad2Amdn38fK",
    "userKey": "NTQkcNfoZLreZk2Ozen31L2DcRbplHvt",
    "encryptionKey": "TFMgVawGSDpd1bA7FukrHRNvEQmugCLk"
}


// Valid up to	3/30/2050 12:00:00 PM

// {   id:"",
// ipoName:"",
// listingAT:"",
// openDate:"",
// closeDate:"",
// listingDate:"",
// offerPrice:"",
// lotSize:"",
// subScriptions:"",
// companyLogo:"",
// companyDetails:""
// },



[
    {
     "role": "admin",
     "fullName": "Gopal Gupta",
     "userName": "Gopal_123",
     "email": "gg@gmail.com",
     "password": "Gopal@123",
     "contactNo": "9892408402",
     "accountNo": "35372883639",
     "pancardNo": "CXVPG1567J",
     "IfscCode": "Sbin0008373",
     "confirmAccountNo": "35372883640",
     "aadharNo": "672326872311",
     "userid": "1",
     "confirmPassword": "",
     "watchList": [],
     "userImage": "file:///data/user/0/com.marketworld/cache/rn_image_picker_lib_temp_7d2caf3d-6c0e-459b-be05-bffdf9f25338.jpg"
    },
    {
     "role": "user",
     "fullName": "Akash",
     "userName": "Akash_123",
     "email": "akashg@gmail.com",
     "password": "Akash@123",
     "contactNo": 2000000002,
     "userid": "2",
     "accountNo": 1212121212,
     "pancardNo": "sadfw4556s",
     "IfscCode": "barb0dbjuhu",
     "confirmAccountNo": 1212121212,
     "aadharNo": 123456789112,
     "watchList": [],
     "userImage": ""
    },
    {
     "role": "user",
     "fullName": "me",
     "userName": "V2stech_123",
     "email": "v2stech@gmail.com",
     "password": "V2stech@123",
     "contactNo": 2000000002,
     "userid": "4",
     "accountNo": 1212121212,
     "pancardNo": "sadfw4556s",
     "IfscCode": "barb0dbjuhu",
     "confirmAccountNo": 1212121212,
     "aadharNo": 123456789112,
     "userImage": "",
     "watchList": []
    },
    {
     "role": "user",
     "fullName": "Dhiraj Gupta ",
     "userName": "Dhiraj_123",
     "email": "dhiraj@gmail.com",
     "password": "Dhiraj@123",
     "contactNo": 5000000005,
     "userid": "5",
     "accountNo": 1212121212,
     "pancardNo": "sadfw4556s",
     "IfscCode": "barb0dbjuhu",
     "confirmAccountNo": 1212121212,
     "aadharNo": 123456789112,
     "userImage": "",
     "watchList": []
    }
   ]

export const ipoList=[
    {   id:"0",
        ipoName:"Sula Vineyards Limited IPO",
        ipoShortTitle:"SVL",
        listingAT:"BSE ,NSE",
        openDate:"2022-12-12",
        closeDate:"2022-12-14",
        allotment:"2022-12-19",
        refundDate:"2022-12-20",
        dematTransfer:"2022-12-20",
        listingDate:"2022-12-22",
        mandateEnd:"2022-12-31",
        offerPrice:"340-357",
        dateRange:"12th - 14th December",
        lotSize:"42",
        subScriptions:"7times",
        companyLogo:"",
        status:"Closed",
        companyDetails:`Incorporated in 2003, Sula Vineyards Limited is the India's largest wine producer and seller as of March 31, 2022. The company also distribute wines under a bouquet of popular brands including "RASA," "Dindori", "The source," "Satori", "Madera" & "Dia" with its flagship brand "Sula" being the "category creator" of wine in India.The company's business is broadly classified under two categories (i) the production of wine, the import of wines and spirits, and the distribution of wines and spirits (the "Wine Business"); and (ii) the sale of services from ownership and operation of wine tourism venues, including vineyard resorts and tasting rooms (the "Wine Tourism Business")`
    },
    {   id:"1",
        ipoName:"Chaman Metallics Limited IPO",
        ipoShortTitle:"CML",
        listingAT:"NSE SME",
        dateRange:"04th - 06th January",
        openDate:"2023-01-04",
        closeDate:"2023-01-06",
        allotment:"2023-01-09",
        refundDate:"2023-01-10",
        dematTransfer:"2023-01-10",
        listingDate:"2023-01-11",
        mandateEnd:"2023-01-21",
        offerPrice:"38.00",
        lotSize:"3000",
        subScriptions:"25times",
        companyLogo:"",
        status:"Closed",
        companyDetails:"Incorporated in 2003, Chaman Metallics Limited is primarily engaged in the business of manufacturing and selling of Direct Reduced Iron (i.e. sponge iron). Sponge iron is mainly used as a raw material for making steel in electric arc furnaces and induction furnaces."
    },
    {   id:"2",
        ipoName:"Ducol Organics And Colours Limited IPO",
        ipoShortTitle:"DOACL",
        listingAT:"NSE SME",
        dateRange:"09th - 11th January",
        openDate:"2023-01-09",
        closeDate:"2023-01-11",
        allotment:"2023-01-17",
        refundDate:"2023-01-18",
        dematTransfer:"2023-01-18",
        listingDate:"2023-01-19",
        mandateEnd:"2023-01-31",
        offerPrice:"78",
        lotSize:"1600",
        subScriptions:"10times",
        companyLogo:"",
        status:"Apply",
        companyDetails:"Incorporated in 1994, Ducol Organics And Colours Limited offer a range of pigment dispersions for various industries. They offer products like Paints, Ink, Textile, Detergent, Paper, Rubber, and Plastics color solutions. They primarily engage in the business of manufacturing and selling of pigment dispersions, preparations, concentrates, paste colorants, and master batches."
    },
    {   id:"3",
        ipoName:"Eastern Logica Infoway Limited IPO",
        ipoShortTitle:"ELIL",
        listingAT:"NSE SME",
        dateRange:"05th - 09th January",
        openDate:"2023-01-05",
        closeDate:"2023-01-09",
        allotment:"2023-01-15",
        refundDate:"2023-01-16",
        dematTransfer:"2023-01-16",
        listingDate:"2023-01-17",
        mandateEnd:"2023-01-30",
        offerPrice:"225",
        lotSize:"600",
        subScriptions:"5times",
        status:"Apply",
        companyLogo:"",
        companyDetails:"The company is in a highly competitive multi-brand retailing and distribution segment. Though it posted growth in its top line, its margins are under pressure. Based on its financial data so far, the issue appears aggressively priced. Small paid-up equity capital base post IPO indicates longer gestation for migration to the mainboard. There is no harm in skipping this pricey bet"
    },
    {   id:"4",
        ipoName:"Sah Polymers Limited IPO",
        ipoShortTitle:"SPL",
        listingAT:"BSE ,NSE",
        dateRange:"30th - 04th January",
        openDate:"2022-12-30",
        closeDate:"2023-01-04",
        allotment:"2023-01-10",
        refundDate:"2023-01-11",
        dematTransfer:"2023-01-11",
        listingDate:"2023-01-12",
        mandateEnd:"2023-01-24",
        offerPrice:"61-65",
        lotSize:"230",
        subScriptions:"12.5times",
        status:"Apply",
        companyLogo:"",
        companyDetails:"The company is operating in a highly competitive segment with two of its group company having an interest in a similar business. There are many other points of concern. Even based on its super earnings the issue is highly-priced. Initial listing in the “T” group may curtail speculative movements in the initial period. There is no harm in skipping this pricy bet"
    },
    {   id:"5",
        ipoName:"Sula Vineyards Limited IPO",
        ipoShortTitle:"SVL",
        listingAT:"BSE ,NSE",
        openDate:"2022-12-12",
        closeDate:"2022-12-14",
        allotment:"2022-12-19",
        refundDate:"2022-12-20",
        dematTransfer:"2022-12-20",
        listingDate:"2022-12-22",
        mandateEnd:"2022-12-31",
        offerPrice:"340-357",
        dateRange:"12th - 14th December",
        lotSize:"42",
        subScriptions:"7times",
        status:"Apply",
        companyLogo:"",
        companyDetails:`Incorporated in 2003, Sula Vineyards Limited is the India's largest wine producer and seller as of March 31, 2022. The company also distribute wines under a bouquet of popular brands including "RASA," "Dindori", "The source," "Satori", "Madera" & "Dia" with its flagship brand "Sula" being the "category creator" of wine in India.The company's business is broadly classified under two categories (i) the production of wine, the import of wines and spirits, and the distribution of wines and spirits (the "Wine Business"); and (ii) the sale of services from ownership and operation of wine tourism venues, including vineyard resorts and tasting rooms (the "Wine Tourism Business")`

    },
    {   id:"6",
        ipoName:"Chaman Metallics Limited IPO",
        ipoShortTitle:"CML",
        listingAT:"NSE SME",
        dateRange:"04th - 06th January",
        openDate:"2023-01-04",
        closeDate:"2023-01-06",
        allotment:"2023-01-09",
        refundDate:"2023-01-10",
        dematTransfer:"2023-01-10",
        listingDate:"2023-01-11",
        mandateEnd:"2023-01-21",
        offerPrice:"38.00",
        lotSize:"3000",
        subScriptions:"25times",
        status:"Apply",
        companyLogo:"",
        companyDetails:"Incorporated in 2003, Chaman Metallics Limited is primarily engaged in the business of manufacturing and selling of Direct Reduced Iron (i.e. sponge iron). Sponge iron is mainly used as a raw material for making steel in electric arc furnaces and induction furnaces."
    },
    {   id:"7",
        ipoName:"Ducol Organics And Colours Limited IPO",
        ipoShortTitle:"DOACL",
        listingAT:"NSE SME",
        dateRange:"09th - 11th January",
        openDate:"2023-01-09",
        closeDate:"2023-01-11",
        allotment:"2023-01-17",
        refundDate:"2023-01-18",
        dematTransfer:"2023-01-18",
        listingDate:"2023-01-19",
        mandateEnd:"2023-01-31",
        offerPrice:"78",
        lotSize:"1600",
        subScriptions:"10times",
        status:"Apply",
        companyLogo:"",
        companyDetails:"Incorporated in 1994, Ducol Organics And Colours Limited offer a range of pigment dispersions for various industries. They offer products like Paints, Ink, Textile, Detergent, Paper, Rubber, and Plastics color solutions. They primarily engage in the business of manufacturing and selling of pigment dispersions, preparations, concentrates, paste colorants, and master batches."
    },
    {   id:"8",
        ipoName:"Eastern Logica Infoway Limited IPO",
        ipoShortTitle:"ELIL",
        listingAT:"NSE SME",
        dateRange:"05th - 09th January",
        openDate:"2023-01-05",
        closeDate:"2023-01-09",
        allotment:"2023-01-15",
        refundDate:"2023-01-16",
        dematTransfer:"2023-01-16",
        listingDate:"2023-01-17",
        mandateEnd:"2023-01-30",
        offerPrice:"225",
        lotSize:"600",
        status:"Closed",
        subScriptions:"5times",
        companyLogo:"",
        companyDetails:"The company is in a highly competitive multi-brand retailing and distribution segment. Though it posted growth in its top line, its margins are under pressure. Based on its financial data so far, the issue appears aggressively priced. Small paid-up equity capital base post IPO indicates longer gestation for migration to the mainboard. There is no harm in skipping this pricey bet"
    },
    {   id:"9",
        ipoName:"Sah Polymers Limited IPO",
        ipoShortTitle:"SPL",
        listingAT:"BSE ,NSE",
        dateRange:"30th - 04th January",
        openDate:"2022-12-30",
        closeDate:"2023-01-04",
        allotment:"2023-01-10",
        refundDate:"2023-01-11",
        dematTransfer:"2023-01-11",
        listingDate:"2023-01-12",
        mandateEnd:"2023-01-24",
        offerPrice:"61-65",
        lotSize:"230",
        subScriptions:"12.5times",
        status:"Closed",
        companyLogo:"",
        companyDetails:"The company is operating in a highly competitive segment with two of its group company having an interest in a similar business. There are many other points of concern. Even based on its super earnings the issue is highly-priced. Initial listing in the “T” group may curtail speculative movements in the initial period. There is no harm in skipping this pricy bet"
    },
]

export const stocks =[
    {
    "stockType":"Indices","type": "nifty",
     "percentageChange":14, "cagr": 25,
     "image": "https://firebasestorage.googleapis.com/v0/b/stocks-images.appspot.com/o/nifty50.png?alt=media&token=b776af0d-2163-4f7b-ad8d-577db79f0a00",
     "chartName": "Nifty",
     "highPrice": 17187,
     "lowPrice": 16747,
     "previousClose": 17094,
     "weeksLow": 16458,
     "weeksHigh": 18090,
     "id": "1"
    },
    {
    "stockType":"Indices","type": "banks",
     "percentageChange":14, "cagr": 25,
     "image": "https://firebasestorage.googleapis.com/v0/b/stocks-images.appspot.com/o/niftybank.png?alt=media&token=5e374f90-022b-4611-9d35-fb25a1685dac",
     "chartName": "Bank Nifty",
     "highPrice": 39500,
     "lowPrice": 37386,
     "previousClose": 37647,
     "weeksLow": 37165,
     "weeksHigh": 41820,
     "id": "2"
    },
    {
    "stockType":"Stocks","type": "others",
     "percentageChange":14, "cagr": 24,
     "image": "https://firebasestorage.googleapis.com/v0/b/stocks-images.appspot.com/o/adaniport.png?alt=media&token=3e1d1952-ac99-45d6-bff1-92034cb9e385",
     "chartName": "Adani port",
     "highPrice": 830,
     "lowPrice": 801,
     "previousClose": 820,
     "weeksLow": 650,
     "weeksHigh": 988,
     "id": "3"
    },
    {
    "stockType":"Stocks","type": "others",
     "percentageChange":14, "cagr": 20.64,
     "image": "https://firebasestorage.googleapis.com/v0/b/stocks-images.appspot.com/o/reliance.png?alt=media&token=85c1a4d4-2ab2-4f52-899b-dd0c3ddf7bcf",
     "chartName": "Reliance",
     "highPrice": 2402,
     "lowPrice": 2311,
     "previousClose": 2325,
     "weeksLow": 2107,
     "weeksHigh": 2700,
     "id": "4"
    },
    {
     "stockType":"Stocks","type": "others",
     "percentageChange":14, "cagr": 14.84,
     "image": "https://firebasestorage.googleapis.com/v0/b/stocks-images.appspot.com/o/sbilife.png?alt=media&token=fc9e3a3f-2a2e-4dae-b4b5-87b380ba3257",
     "chartName": "Sbi life",
     "highPrice": 1289,
     "lowPrice": 1265,
     "previousClose": 1273,
     "weeksLow": 840,
     "weeksHigh": 1415,
     "id": "5"
    },
    {
    "stockType":"Stocks","type": "banks",
     "percentageChange":14, "cagr": 8.38,
     "image": "https://firebasestorage.googleapis.com/v0/b/stocks-images.appspot.com/o/sbin.png?alt=media&token=b840dcea-2cfa-47da-9b58-c42cae231399",
     "chartName": "State Bank of India",
     "highPrice": 536,
     "lowPrice": 516,
     "previousClose": 521,
     "weeksLow": 475,
     "weeksHigh": 575,
     "id": "6"
    },
    {
    "stockType":"Stocks","type": "banks",
     "percentageChange":14, "cagr": 8.27,
     "image": "https://firebasestorage.googleapis.com/v0/b/stocks-images.appspot.com/o/kotakbank.png?alt=media&token=70c7f89a-493e-40e2-a6c3-71072e729f2b",
     "chartName": "Kotak bank",
     "highPrice": 1827,
     "lowPrice": 1757,
     "previousClose": 1765,
     "weeksLow": 1632,
     "weeksHigh": 1980,
     "id": "7"
    },
    {
    "stockType":"Stocks","type": "banks",
     "percentageChange":14, "cagr": 8.27,
     "image": "https://firebasestorage.googleapis.com/v0/b/stocks-images.appspot.com/o/hdfcbank.png?alt=media&token=2b233afa-71f4-452a-8576-f1db990ab6e9",
     "chartName": "Hdfc bank",
     "highPrice": 1431,
     "lowPrice": 1365,
     "previousClose": 1382,
     "weeksLow": 1274,
     "weeksHigh": 1540,
     "id": "8"
    },
    {
    "stockType":"Stocks","type": "it",
     "percentageChange":14, "cagr": 20.64,
     "image": "https://firebasestorage.googleapis.com/v0/b/stocks-images.appspot.com/o/infosys.png?alt=media&token=9ee17499-b0ca-4557-960f-5becdc97dc48",
     "chartName": "Infosys",
     "highPrice": 1419,
     "lowPrice": 1376,
     "previousClose": 1398,
     "weeksLow": 1200,
     "weeksHigh": 1785,
     "id": "9"
    },
    {
    "stockType":"Stocks","type": "auto",
     "percentageChange":14, "cagr": 7.9,
     "image": "https://firebasestorage.googleapis.com/v0/b/stocks-images.appspot.com/o/tatamotors.png?alt=media&token=e8d0e67e-bf07-474f-98ed-2b19ff7076ff",
     "chartName": "Tatamotors",
     "highPrice": 408,
     "lowPrice": 392,
     "previousClose": 404,
     "weeksLow": 376,
     "weeksHigh": 492,
     "id": "10"
    },
    {
    "stockType":"Stocks","type": "power",
     "percentageChange":14, "cagr": 33.36,
     "image": "https://firebasestorage.googleapis.com/v0/b/stocks-images.appspot.com/o/tatapower.png?alt=media&token=45f7a9fd-75b8-4742-9b66-c1db04fc78d7",
     "chartName": "TataPower",
     "highPrice": 217,
     "lowPrice": 210,
     "previousClose": 212,
     "weeksLow": 183,
     "weeksHigh": 250,
     "id": "11"
    },
    {
    "stockType":"Stocks","type": "it",
     "percentageChange":14, "cagr": 33.36,
     "image": "https://firebasestorage.googleapis.com/v0/b/stocks-images.appspot.com/o/tcs.png?alt=media&token=8411c72d-a4ed-4d9c-b220-da8f287b0dff",
     "chartName": "TCS",
     "highPrice": 3019,
     "lowPrice": 2950,
     "previousClose": 2997,
     "weeksLow": 2980,
     "weeksHigh": 3456,
     "id": "12"
    },
    {
    "stockType":"Stocks","type": "it",
     "percentageChange":14, "cagr": 20.32,
     "image": "",
     "chartName": "Wipro",
     "highPrice": 408,
     "lowPrice": 392,
     "previousClose": 404,
     "weeksLow": 376,
     "weeksHigh": 492,
     "id": "13"
    },
    {
    "stockType":"Stocks","type": "it",
     "percentageChange":14, "cagr": 19.9,
     "image": "",
     "chartName": "Happistsmind",
     "highPrice": 408,
     "lowPrice": 392,
     "previousClose": 404,
     "weeksLow": 376,
     "weeksHigh": 492,
     "id": "14"
    },
    {
    "stockType":"Stocks","type": "it",
     "percentageChange":14, "cagr": 19.9,
     "image": "",
     "chartName": "Tech mahindra",
     "highPrice": 408,
     "lowPrice": 392,
     "previousClose": 404,
     "weeksLow": 376,
     "weeksHigh": 492,
     "id": "15"
    },
    {
    "stockType":"Stocks","type": "it",
     "percentageChange":14, "cagr": 20.32,
     "image": "",
     "chartName": "Mindtree",
     "highPrice": 408,
     "lowPrice": 392,
     "previousClose": 404,
     "weeksLow": 376,
     "weeksHigh": 492,
     "id": "16"
    },
    {
    "stockType":"Stocks","type": "banks",
     "percentageChange":14, "cagr": "15.50",
     "image": "",
     "chartName": "Axis Bank",
     "highPrice": "470",
     "lowPrice": 392,
     "previousClose": 404,
     "weeksLow": 376,
     "weeksHigh": 492,
     "id": "17"
    },
    {
    "stockType":"Stocks","type": "banks",
     "percentageChange":14, "cagr": 8.38,
     "image": "",
     "chartName": "ICICI Bank",
     "highPrice": 408,
     "lowPrice": 392,
     "previousClose": 404,
     "weeksLow": 376,
     "weeksHigh": 492,
     "id": "18"
    },
    {
    "stockType":"Stocks","type": "power",
     "percentageChange":14, "cagr": 12.46,
     "image": "",
     "chartName": "NTPC",
     "highPrice": 408,
     "lowPrice": 392,
     "previousClose": 404,
     "weeksLow": 376,
     "weeksHigh": 492,
     "id": "19"
    },
    {
    "stockType":"Stocks","type": "power",
     "percentageChange":14, "cagr": 12.28,
     "image": "",
     "chartName": "Adani power",
     "highPrice": 408,
     "lowPrice": 392,
     "previousClose": 404,
     "weeksLow": 376,
     "weeksHigh": 492,
     "id": "20"
    },
    {
    "stockType":"Stocks","type": "power",
     "percentageChange":14, "cagr": 12.46,
     "image": "",
     "chartName": "JSW Energy",
     "highPrice": 408,
     "lowPrice": 392,
     "previousClose": 404,
     "weeksLow": 376,
     "weeksHigh": 492,
     "id": "21"
    },
    {
    "stockType":"Stocks","type": "power",
     "percentageChange":14, "cagr": 12.46,
     "image": "",
     "chartName": "JP power",
     "highPrice": 408,
     "lowPrice": 392,
     "previousClose": 404,
     "weeksLow": 376,
     "weeksHigh": 492,
     "id": "22"
    },
    {
    "stockType":"Stocks","type": "power",
     "percentageChange":14, "cagr": 12.28,
     "image": "",
     "chartName": "Rpower",
     "highPrice": 26,
     "lowPrice": 24,
     "previousClose": 24.6,
     "weeksLow": 12.5,
     "weeksHigh": 27,
     "id": "23"
    },
    {
    "stockType":"Stocks","type": "others",
     "percentageChange":14, "cagr": 14,
     "image": "",
     "chartName": "HAL",
     "highPrice": 408,
     "lowPrice": 392,
     "previousClose": 404,
     "weeksLow": 376,
     "weeksHigh": 492,
     "id": "24"
    },
    {
    "stockType":"Stocks","type": "others",
     "percentageChange":14, "cagr": 14,
     "image": "",
     "chartName": "Paras Defence",
     "highPrice": 408,
     "lowPrice": 392,
     "previousClose": 404,
     "weeksLow": 376,
     "weeksHigh": 492,
     "id": "25"
    },
    {
    "stockType":"Stocks","type": "others",
     "percentageChange":14, "cagr": 14,
     "image": "",
     "chartName": "Affle India",
     "highPrice": 408,
     "lowPrice": 392,
     "previousClose": 404,
     "weeksLow": 376,
     "weeksHigh": 492,
     "id": "26"
    },
    {
    "stockType":"Stocks","type": "pharma",
     "percentageChange":14, "cagr": 9.45,
     "image": "",
     "chartName": "Sunpharma",
     "highPrice": 408,
     "lowPrice": 392,
     "previousClose": 404,
     "weeksLow": 376,
     "weeksHigh": 492,
     "id": "27"
    },
    {
    "stockType":"Stocks","type": "pharma",
     "percentageChange":14, "cagr": 9.45,
     "image": "",
     "chartName": "cipla",
     "highPrice": 408,
     "lowPrice": 392,
     "previousClose": 404,
     "weeksLow": 376,
     "weeksHigh": 492,
     "id": "28"
    },
    {
    "stockType":"Stocks","type": "pharma",
     "percentageChange":14, "cagr": 9.45,
     "image": "",
     "chartName": "Lauras Lab",
     "highPrice": 408,
     "lowPrice": 392,
     "previousClose": 404,
     "weeksLow": 376,
     "weeksHigh": 492,
     "id": "29"
    },
    {
    "stockType":"Stocks","type": "pharma",
     "percentageChange":14, "cagr": 9.4,
     "image": "",
     "chartName": "Glenmark pharma",
     "highPrice": 408,
     "lowPrice": 392,
     "previousClose": 404,
     "weeksLow": 376,
     "weeksHigh": 492,
     "id": "30"
    },
    {
    "stockType":"Stocks","type": "pharma",
     "percentageChange":14, "cagr": 9.45,
     "image": "",
     "chartName": "Dr.Reddy's Laborartries",
     "highPrice": 408,
     "lowPrice": 392,
     "previousClose": 404,
     "weeksLow": 376,
     "weeksHigh": 492,
     "id": "31"
    },
    {
    "stockType":"Stocks","type": "others",
     "percentageChange":14, "cagr": 2.02,
     "image": "",
     "chartName": "ICICI PRU Life",
     "highPrice": 408,
     "lowPrice": 392,
     "previousClose": 404,
     "weeksLow": 376,
     "weeksHigh": 492,
     "id": "32"
    },
    {
    "stockType":"Stocks","type": "others",
     "percentageChange":14, "cagr": 2.02,
     "image": "",
     "chartName": "HDFC Life",
     "highPrice": 408,
     "lowPrice": 392,
     "previousClose": 404,
     "weeksLow": 376,
     "weeksHigh": 492,
     "id": "33"
    },
    {
    "stockType":"Stocks","type": "metals",
     "percentageChange":14, "cagr": 14,
     "image": "",
     "chartName": "Sail",
     "highPrice": 408,
     "lowPrice": 392,
     "previousClose": 404,
     "weeksLow": 376,
     "weeksHigh": 492,
     "id": "34"
    },
    {
    "stockType":"Stocks","type": "metals",
     "percentageChange":14, "cagr": 33.36,
     "image": "",
     "chartName": "Tata Steel",
     "highPrice": 408,
     "lowPrice": 392,
     "previousClose": 404,
     "weeksLow": 376,
     "weeksHigh": 492,
     "id": "35"
    },
    {
    "stockType":"Stocks","type": "metals",
     "percentageChange":14, "cagr": 14,
     "image": "",
     "chartName": "JSW steel",
     "highPrice": 408,
     "lowPrice": 392,
     "previousClose": 404,
     "weeksLow": 376,
     "weeksHigh": 492,
     "id": "36"
    },
    {
    "stockType":"Stocks","type": "metals",
     "percentageChange":14, "cagr": 12.9,
     "image": "",
     "chartName": "Vedanta",
     "highPrice": 408,
     "lowPrice": 392,
     "previousClose": 404,
     "weeksLow": 376,
     "weeksHigh": 492,
     "id": "37"
    },
    {
    "stockType":"Stocks","type": "metals",
     "percentageChange":14, "cagr": 14,
     "image": "",
     "chartName": "JINDAL STEEL",
     "highPrice": 408,
     "lowPrice": 392,
     "previousClose": 404,
     "weeksLow": 376,
     "weeksHigh": 492,
     "id": "38"
    },
    {
    "stockType":"Stocks","type": "others",
     "percentageChange":14, "cagr": 14,
     "image": "",
     "chartName": " IRCTC",
     "highPrice": 408,
     "lowPrice": 392,
     "previousClose": 404,
     "weeksLow": 376,
     "weeksHigh": 492,
     "id": "39"
    },
    {
    "stockType":"Stocks","type": "fmcg",
     "percentageChange":14, "cagr": 20.89,
     "image": "",
     "chartName": "HUL",
     "highPrice": 408,
     "lowPrice": 392,
     "previousClose": 404,
     "weeksLow": 376,
     "weeksHigh": 492,
     "id": "40"
    },
    {
    "stockType":"Stocks","type": "fmcg",
     "percentageChange":14, "cagr": 20.64,
     "image": "",
     "chartName": "ITC",
     "highPrice": 408,
     "lowPrice": 392,
     "previousClose": 404,
     "weeksLow": 376,
     "weeksHigh": 492,
     "id": "41"
    },
    {
    "stockType":"Stocks","type": "fmcg",
     "percentageChange":14, "cagr": 12.36,
     "image": "",
     "chartName": "Bector's Food",
     "highPrice": 408,
     "lowPrice": 392,
     "previousClose": 404,
     "weeksLow": 376,
     "weeksHigh": 492,
     "id": "42"
    },
    {
    "stockType":"Stocks","type": "others",
     "percentageChange":14, "cagr": 4.5,
     "image": "",
     "chartName": "AMARRAJABATTRIES",
     "highPrice": 408,
     "lowPrice": 392,
     "previousClose": 404,
     "weeksLow": 376,
     "weeksHigh": 492,
     "id": "43"
    },
    {
    "stockType":"Stocks","type": "commodities",
     "percentageChange":14, "cagr": "13",
     "image": "",
     "chartName": "copper",
     "highPrice": 614.1,
     "id": "50"
    },
    {
    "stockType":"Stocks","type": "commodities",
     "percentageChange":14, "cagr": 14,
     "image": "",
     "chartName": "Silver",
     "highPrice": 57.98,
     "id": "51"
    },
    {
    "stockType":"Indices","type": "nifty",
     "percentageChange":14, "cagr": 12,
     "image": "",
     "chartName": "niftyIt",
     "highPrice": "18100",
     "id": "52"
    },
    {
    "stockType":"ETF","type": "etf",
     "percentageChange":14, "cagr": 14.03,
     "image": "",
     "chartName": "NiftyBees",
     "highPrice": 173.89,
     "id": "53"
    },
    {
    "stockType":"ETF","type": "etf",
     "percentageChange":14, "cagr": 14.03,
     "image": "",
     "chartName": "GoldBees",
     "highPrice": 43.18,
     "id": "54"
    },
    {
    "stockType":"ETF","type": "etf",
     "percentageChange":14, "cagr": 12.45,
     "image": "",
     "chartName": "JuniorBees",
     "highPrice": 409.74,
     "id": "55"
    },
    {
    "stockType":"ETF","type": "etf",
     "percentageChange":14, "cagr": 14,
     "image": "",
     "chartName": "kotakkit",
     "highPrice": 55.45,
     "id": "56"
    },
    {
    "stockType":"ETF","type": "etf",
     "percentageChange":14, "cagr": 14,
     "image": "",
     "chartName": "Kotak Midcap50",
     "highPrice": 77.45,
     "id": "57"
    },
    {
    "stockType":"ETF","type": "etf",
     "percentageChange":14, "cagr": 14,
     "image": "",
     "chartName": "Kotak Nifty",
     "highPrice": 169.64,
     "id": "58"
    },
    {
    "stockType":"ETF","type": "etf",
     "percentageChange":14, "cagr": 14,
     "image": "",
     "chartName": "ICICI prudential ETF",
     "highPrice": 72.91,
     "id": "59"
    },
    {
    "stockType":"Mutual Funds","type": "mutualfunds",
     "percentageChange":14, "cagr": 83,
     "image": "",
     "chartName": "Green Energy",
     "highPrice": 57283,
     "id": "60"
    },
    {
    "stockType":"Mutual Funds","type": "mutualfunds",
     "percentageChange":14, "cagr": 49.79,
     "image": "",
     "chartName": "Wright Momentum",
     "highPrice": 61231,
     "id": "61"
    },
    {
    "stockType":"Mutual Funds","type": "mutualfunds",
     "percentageChange":14, "cagr": 40.89,
     "chartName": "Negen Opporunities",
     "highPrice": 60550,
     "id": "62"
    },
    {
    "stockType":"Mutual Funds","type": "mutualfunds",
     "percentageChange":14, "cagr" :65.99,
     "image": "",
     "chartName": "High Quality Right Price",
     "highPrice": 20654,
     "id": "63"
    },
    {
    "stockType":"Mutual Funds","type": "mutualfunds",
     "percentageChange":14, "cagr": 14,
     "image": "",
     "chartName": "ICICI Prudential AMC",
     "highPrice": 772,
     "id": "64"
    },
    {
    "stockType":"Mutual Funds","type": "mutualfunds",
     "percentageChange":14, "cagr": 55.45,
     "image": "",
     "chartName": "High Dividend yield & capital",
     "highPrice": 37391,
     "id": "65"
    },
    
    {
    "stockType":"Bonds","type": "bonds",
     "percentageChange":14, "cagr": 4,
     "image": "",
     "chartName": "Soverign gold bond",
     "highPrice": 37391,
     "id": "66"
    },
    {
    "stockType":"Bonds","type": "bonds",
     "percentageChange":14, "cagr": 12,
     "image": "",
     "chartName": "Gold bond",
     "highPrice": 37391,
     "id": "66"
    },
    {
    "stockType":"Bonds","type": "bonds",
     "percentageChange":14, "cagr": 25,
     "image": "",
     "chartName": "Infrastructure Bonds",
     "highPrice": 37391,
     "id": "67"
    },

   ]

export const membersDetails=[
    {
     "role": "admin",
     "fullName": "Gopal Gupta",
     "userName": "Gopal_123",
     "email": "gg@gmail.com",
     "password": "Gopal@123",
     "contactNo": "9892408402",
     "accountNo": "35372883639",
     "pancardNo": "CXVPG1567J",
     "IfscCode": "Sbin0008373",
     "confirmAccountNo": "35372883640",
     "aadharNo": "672326872311",
     "userid": "1",
     "confirmPassword": "",
     "userImage":""
    },
    {
     "role": "user",
     "fullName": "Akash",
     "userName": "Akash_123",
     "email": "akashg@gmail.com",
     "password": "Akash@123",
     "contactNo": 2000000002,
     "userid": "2",
     "accountNo": 1212121212,
     "pancardNo": "sadfw4556s",
     "IfscCode": "barb0dbjuhu",
     "confirmAccountNo": 1212121212,
     "aadharNo": 123456789112,
     "userImage":""

    },
    {
     "role": "user",
     "fullName": "Vikash",
     "userName": "Vikash_123",
     "email": "vikash@gmail.com",
     "password": "Vikash@123",
     "contactNo": 3000000003,
     "userid": "3",
     "accountNo": 1212121212,
     "pancardNo": "sadfw4556s",
     "IfscCode": "barb0dbjuhu",
     "confirmAccountNo": 1212121212,
     "aadharNo": 123456789112,
     "userImage":""

    },
    {
     "role": "user",
     "fullName": "me",
     "userName": "V2stech_123",
     "email": "v2stech@gmail.com",
     "password": "V2stech@123",
     "contactNo": 2000000002,
     "userid": "4",
     "accountNo": 1212121212,
     "pancardNo": "sadfw4556s",
     "IfscCode": "barb0dbjuhu",
     "confirmAccountNo": 1212121212,
     "aadharNo": 123456789112,
     "userImage":""

    },
    {
     "role": "user",
     "fullName": "Dhiraj Gupta ",
     "userName": "Dhiraj_123",
     "email": "dhiraj@gmail.com",
     "password": "Dhiraj@123",
     "contactNo": 5000000005,
     "userid": "5",
     "accountNo": 1212121212,
     "pancardNo": "sadfw4556s",
     "IfscCode": "barb0dbjuhu",
     "confirmAccountNo": 1212121212,
     "aadharNo": 123456789112,
     "userImage":""

    },
    {
     "role": "user",
     "fullName": "Satish",
     "userName": "Satish_123",
     "email": "satish@gmail.com",
     "password": "Satish@123",
     "contactNo": 1234567890,
     "accountNo": "accountNo 6",
     "pancardNo": "pancardNo 6",
     "IfscCode": "IfscCode 6",
     "confirmAccountNo": "confirmAccountNo 6",
     "aadharNo": "aadharNo 6",
     "userid": "6",
     "confirmPassword": "Satish@123",
     "userImage":""

    },
    {
     "role": "user",
     "fullName": "Tester1 V2STech",
     "userName": "V2stech_0183",
     "email": "v2stechtester1@gmail.com",
     "password": "V2stech@0183",
     "contactNo": "123456789",
     "accountNo": "accountNo 7",
     "pancardNo": "pancardNo 7",
     "IfscCode": "IfscCode 7",
     "confirmAccountNo": "confirmAccountNo 7",
     "aadharNo": "aadharNo 7",
     "userid": "7",
     "confirmPassword": "V2stech@0183",
     "userImage":""
    }
   ]
